function out1 = Planar6R_HT_link_2(in1)
%Planar6R_HT_link_2
%    OUT1 = Planar6R_HT_link_2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    27-Feb-2026 19:37:29

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
out1 = reshape([t3,t4,0.0,0.0,-t4,t3,0.0,0.0,0.0,0.0,1.0,0.0,t3.*(1.1e+1./2.0e+1)+cos(q1).*(1.3e+1./2.0e+1),t4.*(1.1e+1./2.0e+1)+sin(q1).*(1.3e+1./2.0e+1),0.0,1.0],[4,4]);
end
