function out1 = Planar6R_HT_link_1(in1)
%Planar6R_HT_link_1
%    OUT1 = Planar6R_HT_link_1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    27-Feb-2026 19:37:28

q1 = in1(1,:);
t2 = cos(q1);
t3 = sin(q1);
out1 = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(1.3e+1./2.0e+1),t3.*(1.3e+1./2.0e+1),0.0,1.0],[4,4]);
end
