function out1 = Planar6R_Jdot_func_task(in1)
%Planar6R_Jdot_func_task
%    OUT1 = Planar6R_Jdot_func_task(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    27-Feb-2026 19:37:29

dq1 = in1(7,:);
dq2 = in1(8,:);
dq3 = in1(9,:);
dq4 = in1(10,:);
dq5 = in1(11,:);
dq6 = in1(12,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
t2 = dq1+dq2;
t3 = q1+q2;
t4 = dq3+t2;
t5 = cos(t3);
t6 = q3+t3;
t7 = sin(t3);
t8 = cos(t6);
t9 = q4+t6;
t10 = sin(t6);
t11 = dq4+t4;
t22 = t2.*t5.*(1.1e+1./2.0e+1);
t23 = t2.*t7.*(1.1e+1./2.0e+1);
t12 = dq5+t11;
t13 = cos(t9);
t14 = q5+t9;
t15 = sin(t9);
t24 = -t22;
t25 = -t23;
t26 = t4.*t8.*(9.0./2.0e+1);
t27 = t4.*t10.*(9.0./2.0e+1);
t16 = q6+t14;
t17 = sin(t14);
t18 = dq6+t12;
t19 = cos(t14);
t28 = -t26;
t29 = -t27;
t30 = t11.*t13.*(9.0./2.0e+1);
t31 = t11.*t15.*(9.0./2.0e+1);
t20 = cos(t16);
t21 = sin(t16);
t32 = -t30;
t33 = -t31;
t34 = t12.*t19.*(9.0./2.0e+1);
t35 = t12.*t17.*(9.0./2.0e+1);
t36 = -t34;
t37 = -t35;
t38 = t18.*t20.*(9.0./2.0e+1);
t39 = t18.*t21.*(9.0./2.0e+1);
t40 = -t38;
t41 = -t39;
out1 = reshape([t24+t28+t32+t36+t40-dq1.*cos(q1).*(1.3e+1./2.0e+1),t25+t29+t33+t37+t41-dq1.*sin(q1).*(1.3e+1./2.0e+1),0.0,t24+t28+t32+t36+t40,t25+t29+t33+t37+t41,0.0,t28+t32+t36+t40,t29+t33+t37+t41,0.0,t32+t36+t40,t33+t37+t41,0.0,t36+t40,t37+t41,0.0,t40,t41,0.0],[3,6]);
end
