function out1 = Planar6R_HT_link_3(in1)
%Planar6R_HT_link_3
%    OUT1 = Planar6R_HT_link_3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    27-Feb-2026 19:37:29

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = q3+t2;
t4 = cos(t3);
t5 = sin(t3);
out1 = reshape([t4,t5,0.0,0.0,-t5,t4,0.0,0.0,0.0,0.0,1.0,0.0,t4.*(9.0./2.0e+1)+cos(q1).*(1.3e+1./2.0e+1)+cos(t2).*(1.1e+1./2.0e+1),t5.*(9.0./2.0e+1)+sin(q1).*(1.3e+1./2.0e+1)+sin(t2).*(1.1e+1./2.0e+1),0.0,1.0],[4,4]);
end
