function out1 = Planar6R_HT_hand_func(in1)
%Planar6R_HT_hand_func
%    OUT1 = Planar6R_HT_hand_func(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    27-Feb-2026 19:37:29

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
t2 = q1+q2;
t3 = q3+t2;
t4 = q4+t3;
t5 = q5+t4;
t6 = q6+t5;
t7 = cos(t6);
t8 = sin(t6);
out1 = reshape([t7,t8,0.0,0.0,-t8,t7,0.0,0.0,0.0,0.0,1.0,0.0,t7.*(9.0./2.0e+1)+cos(q1).*(1.3e+1./2.0e+1)+cos(t2).*(1.1e+1./2.0e+1)+cos(t3).*(9.0./2.0e+1)+cos(t4).*(9.0./2.0e+1)+cos(t5).*(9.0./2.0e+1),t8.*(9.0./2.0e+1)+sin(q1).*(1.3e+1./2.0e+1)+sin(t2).*(1.1e+1./2.0e+1)+sin(t3).*(9.0./2.0e+1)+sin(t4).*(9.0./2.0e+1)+sin(t5).*(9.0./2.0e+1),0.0,1.0],[4,4]);
end
