function out1 = Planar6R_J_func_task(in1)
%Planar6R_J_func_task
%    OUT1 = Planar6R_J_func_task(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    27-Feb-2026 19:37:29

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = q4+t4;
t8 = sin(t4);
t17 = t3.*(1.1e+1./2.0e+1);
t18 = t5.*(1.1e+1./2.0e+1);
t9 = cos(t7);
t10 = q5+t7;
t11 = sin(t7);
t19 = -t18;
t20 = t6.*(9.0./2.0e+1);
t21 = t8.*(9.0./2.0e+1);
t12 = q6+t10;
t13 = sin(t10);
t14 = cos(t10);
t22 = -t21;
t23 = t9.*(9.0./2.0e+1);
t24 = t11.*(9.0./2.0e+1);
t15 = cos(t12);
t16 = sin(t12);
t25 = t14.*(9.0./2.0e+1);
t26 = t13.*(9.0./2.0e+1);
t27 = -t24;
t28 = -t26;
t29 = t15.*(9.0./2.0e+1);
t30 = t16.*(9.0./2.0e+1);
t31 = -t30;
out1 = reshape([t19+t22+t27+t28+t31-sin(q1).*(1.3e+1./2.0e+1),t17+t20+t23+t25+t29+cos(q1).*(1.3e+1./2.0e+1),1.0,t19+t22+t27+t28+t31,t17+t20+t23+t25+t29,1.0,t22+t27+t28+t31,t20+t23+t25+t29,1.0,t27+t28+t31,t23+t25+t29,1.0,t28+t31,t25+t29,1.0,t31,t29,1.0],[3,6]);
end
